[app]
# LLM used for internal operations, like deriving conversation names
fast_llm = "ollama/qwen3:30b-a3b-fp16" ### NOTE - RECOMMENDED TO USE `openai` with `api_base = "http://localhost:11434/v1"` for best results, otherwise `ollama` with `litellm` is acceptable

# LLM used for user-facing output, like RAG replies
quality_llm = "ollama/qwen3:30b-a3b-fp16"

# LLM used for ingesting visual inputs
vlm = "ollama/qwen2.5vl:32b-fp16" # TODO - Replace with viable candidate


# Reasoning model, used for `research` agent
reasoning_llm = "ollama/qwen3:30b-a3b-fp16"
# Planning model, used for `research` agent
planning_llm = "ollama/qwen3:30b-a3b-fp16"


  [app.max_upload_size_by_type]
    txt  = 2000000
    md   = 2000000
    tsv  = 2000000
    csv  = 5000000
    html = 5000000
    doc  = 10000000
    docx = 10000000
    ppt  = 20000000
    pptx = 20000000
    xls  = 10000000
    xlsx = 10000000
    odt  = 5000000
    pdf  = 300000000
    eml  = 5000000
    msg  = 5000000
    p7s  = 5000000
    bmp  = 5000000
    heic = 5000000
    jpeg = 5000000
    jpg  = 5000000
    png  = 5000000
    tiff = 5000000
    epub = 10000000
    rtf  = 5000000
    rst  = 5000000
    org  = 5000000

[embedding]
provider = "ollama"
base_model = "nomic-embed-text"
base_dimension = 768
batch_size = 128
concurrent_request_limit = 5

[completion_embedding]
provider = "ollama"
base_model = "nomic-embed-text"
base_dimension = 768
batch_size = 128
concurrent_request_limit = 5

[agent]
tools = ["search_file_knowledge"]

[completion]
provider = "litellm"
concurrent_request_limit = 5

  [completion.generation_config]
  temperature = 0.1
  top_p = 1
  max_tokens_to_sample = 1_024
  stream = false
  api_base = "http://host.docker.internal:11434"

[ingestion]
provider = "unstructured_local"
strategy = "auto"
new_after_n_chars = 512
max_characters = 1_024
combine_under_n_chars = 128
overlap = 20
chunks_for_document_summary = 16
document_summary_model = "ollama/qwen2.5vl:32b-fp16"
automatic_extraction = false

[orchestration]
provider = "hatchet"